### ISSUE TITLE
Named routes not working in standalone mode

### ISSUE THREAD

**Issue by wirtsi** [leedavis81/drest#22]
Hello
Your framework looks promising, but I had some trouble getting it to work. Routes with params in them did not work correctly
So something like this
```
 *          @Drest\Route(
 *              name="get_brand",
 *              routePattern="/brands/:id",
 *              routeConditions={"id": "\d+"},
 *              verbs={"GET"}
 *          ),
```
and using a bootstrap like this
```
<?php
// bootstrap.php
use Doctrine\ORM\EntityManager;
use Drest\Configuration;
use Drest\Event;

require_once "vendor/autoload.php";

// Create a simple "default" Doctrine ORM configuration for Annotations
$isDevMode = true;

// Create an example doctrine application
$ormConfig = new \Doctrine\ORM\Configuration();
$pathToEntities = array(__DIR__ . '/src/');
$ORMDriver = $ormConfig->newDefaultAnnotationDriver($pathToEntities, false);
$ormConfig->setMetadataDriverImpl($ORMDriver);

// Other various configuration options..
$ormConfig->setProxyDir(__DIR__ . '/Entities/Proxies');
$ormConfig->setProxyNamespace('Entities\Proxies');
$ormConfig->setAutoGenerateProxyClasses(true);


// the connection configuration
$dbParams = array(
    'driver'   => 'pdo_mysql',
    'user'     => 'foo',
    'password' => 'foo',
    'dbname'   => 'phpapi',
);

$em = EntityManager::create($dbParams, $ormConfig);

$drestConfig = new Configuration();
$drestConfig->setDetectContentOptions(array(
    Configuration::DETECT_CONTENT_HEADER => 'Accept',
    Configuration::DETECT_CONTENT_EXTENSION => true,
    Configuration::DETECT_CONTENT_PARAM => 'format'
));
$drestConfig->setExposureDepth(3);
$drestConfig->setExposeRequestOption(Configuration::EXPOSE_REQUEST_PARAM_GET, 'expose');
$drestConfig->setMetadataCacheImpl(new \Doctrine\Common\Cache\ArrayCache());
$drestConfig->setDebugMode(true);
$drestConfig->addPathsToConfigFiles($pathToEntities);
// Set up event manager
$evm = new Event\Manager();
//$evm->addEventListener(array('preServiceAction', 'postServiceAction', 'preRouting', 'postRouting', 'preDispatch', 'postDispatch'), new MyEvents\MyEvent());
$emr = \Drest\EntityManagerRegistry::getSimpleManagerRegistry($em);
$drestManager = \Drest\Manager::create($emr, $drestConfig, $evm);
echo $drestManager->dispatch();
```
(so this uses the default HttpFoundation lib, which is installed)
a call to /brands/1 would never see the param. Strangely, calling 
```
echo $drestManager->dispatch(null, null, "Brands::get_brand", array('id'=>1));
```
works

To fix this, I had to add the following line to MappingRouteMetaData.php -> matcher method
```
$this->route_params = $matcher->getRouteParams();
```

Bests

**Comment by leedavis81** [comment]
Hi @wirtsi, 

   So the following:

    echo $drestManager->dispatch(null, null, "Brands::get_brand", array('id'=>1));

actually bypasses the internal router. You're explicitly stating what route you want to call, and passing in the relevant parameters. This implementation:

    echo $drestManager->dispatch();

Uses the internal router, and which should then provide (as long as your web server is forwarding all your requests to this file ie apache RewriteRule) all matched parameters to the param_names variable on the  relevant Drest\Mapping\RouteMetaData object should be written to the request object. Can you try retrieving the value like so:

    $drestManager->getRequest()->getRouteParam('id')

This should give you what you need. The param_names variable on the manager object should really be internal. Did you see any issues with the request being routed properly?

Regards, 

Lee

**Comment by wirtsi** [comment]
Hi Lee ... thanks for your response.

It indeed was the built in PHP server I'm using. You need to pass the bootstrap script to it, then everything works fine

```
php -S localhost:8000 bootstrap.php
```

Bests
wirtsi

btw, I would greatly appreciate if you could shed some light on https://github.com/leedavis81/drest-client/issues/1 ;)
